### ISSUE TITLE
addLayer method not working correctly.

### ISSUE THREAD

**Issue by HWORX** [aliyilmaz/Mind#13]
im writing $this->addLayer('app/api/Redirect');
yes thats working. But not work for $variables 

Redirect.php contains:

$demo = 'demourl.com';

Get.php contains:

$this->addLayer('app/api/Redirect');

//echo $demo; *gives undefined variable

$left = "";
$right = "";
$get = $this->get_contents($left, $right, $demo);
/* and this gives undefined variable error either */

Thanks in advance dear yilmaz.

**Comment by aliyilmaz** [comment]
You can try like this.

```php
include('app/api/Redirect.php');
```
or

```php
$this->addLayer([
    'app/api/Redirect',
    'app/api/Get'
]);
```
