### ISSUE TITLE
about get_contents method and posting value

### ISSUE THREAD

**Issue by HWORX** [aliyilmaz/Mind#14]
$options = array(
'post'=>array(
'demo'=>'demo',
),
);

thats working okey. But this;

$options = array(
'post'=>array(
'demo'=>'demo',
'Demo2'=>array(
'Demo3'=>'demo3',
),
 ),
   );

ie http_build_query in Mind.php doesn't work when multiple array is used.  I'm waiting for a response for this error.

Regards to my best teacher
-hakan t.

**Comment by aliyilmaz** [comment]
Such use is not specified in the document. The `post` sub-attribute is for adding parameters to a POST request.

**Comment by HWORX** [comment]
mmm.  
I am also sending a POST data in the form of 'region'=>'Turkey'.  When I look at the http_build_query output, it sees the ((&reg)) part as a symbol because it is of the form &region= .  I fixed it by using htmlspecialchars or something, but still no results.  Will these problems be solved?  Shall I wait?
