### ISSUE TITLE
mysql error using prepare function

### ISSUE THREAD

**Issue by gobseck0** [aliyilmaz/Mind#2]
Hi, I I'm not sure what I'm doing wrong, I'm trying to do a query by "prepare" function, my vars are: $name = 'admin'; and $psw = 'root'; but mysql shows an error:  

$result = $db->prepare($sql);
// var_dump($sql);  =  'SELECT id FROM admin WHERE name = 'admin' AND psw ='root''

'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '&#039;admin&#039; AND psw =&#039;root&#039' at line 1'

I just update the function name from the past Mind 1.0 (querySQL) function.

**Comment by gobseck0** [comment]
Thanks for the update, only one more thing. Do you think is possible to update your createtable and createcolumn functions with an extended library for "int" and "decimal" tables? maybe not for now, but it will be really useful if you can. Cheers!

**Comment by aliyilmaz** [comment]
Hello, thank you for your interest and understanding, I've added to my to-do list.

**Comment by aliyilmaz** [comment]
> $result = $db->prepare($sql);
> // var_dump($sql); = 'SELECT id FROM admin WHERE name = 'admin' AND psw ='root''
-----------------

You can create this query without typing sql.

```
$arr = array(
    'search'=>array(
        'equal'=>array(
            'name'=>'admin',
            'psq'=>'root'
        )
    )
);
echo '<pre>';
print_r($db->get('admin', $arr));
echo '</pre>';

```
OR

```
$arr = array(
    'search'=>array(
        'column'=>'id',
        'equal'=>array(
            'name'=>'admin',
            'psq'=>'root'
        )
    )
);
echo '<pre>';
print_r($db->get('admin', $arr));
echo '</pre>';
```
I'm sorry I couldn't provide an English source for more information.You can browse for more about  ['Equal'](https://github.com/aliyilmaz/Mind#searchequal-%C3%A7oklu-e%C5%9Fitlik-denklemi)

**Comment by aliyilmaz** [comment]
> Do you think is possible to update your createtable and createcolumn functions with an extended library for "int" and "decimal" tables? maybe not for now, but it will be really useful if you can. 

Thank you very much for your nice advice.  :1st_place_medal:  I made the update. :100:
https://github.com/aliyilmaz/Mind/blob/master/tests/createtable.php
https://github.com/aliyilmaz/Mind/blob/master/tests/createcolumn.php

**Comment by gobseck0** [comment]
> > Do you think is possible to update your createtable and createcolumn functions with an extended library for "int" and "decimal" tables? maybe not for now, but it will be really useful if you can.
> 
> Thank you very much for your nice advice. 🥇 I made the update. 💯
> https://github.com/aliyilmaz/Mind/blob/master/tests/createtable.php
> https://github.com/aliyilmaz/Mind/blob/master/tests/createcolumn.php

Superb!! Thanks a lot!!

**Comment by gobseck0** [comment]
Hi! I have an issue with the createtable(); function, I cannot make it work if you create the array ($scheme) from a fetch loop:

$tablename = '2_1_5C';
$arraysy = array();
$start= "'idc:int'";  // first data in array
array_push ($arraysy,$start);
$getdata = $this->prepare("SELECT id,scores FROM $tablename");
while ($res = mysqli_fetch_array($getdata)){
	$var2 = $res['scores']." ";  // the table have this info:  id: 1, 2, 3, 4, 5  scores: 10,10,2,2,1
	$var1 = $res['id'];
	for ($i = 1; $var2 >= $i; $i++ ){
	$vari = "'".$var1."_".$i.":decimal:3,2'"; // this create something like:  '1_1:decimal:3,2' 
	array_push($arraysy,$vari);
	}
};
$end=  "'activo:int'";  //  the last record in the tables array
array_push ($arraysy,$end); 
$scheme0 = implode (",", $arraysy);  //  this put a "," at the end of each data
$scheme = array($scheme0);
$this->createtable($tablename, $scheme); 
---------------
This show the following error:
public 'errno' => int 1146
public 'error' => string 'Table 'mygrades.2_1_5c' doesn't exist' (length=37)

Do you know how can I build the $scheme array by a loop?

Thanks in advance.

**Comment by aliyilmaz** [comment]
> Hi! I have an issue with the createtable(); function, I cannot make it work if you create the array ($scheme) from a fetch loop:
> 
> Do you know how can I build the $scheme array by a loop?
> 
> Thanks in advance.

Hi, if I understand correctly, you want to do something like this?
```
$tablename = '2_1_5C';

$scheme = array();
$scheme[] = 'idc:int'; //idc:increments ?

$arr = array(
    'column'=>array('id', 'scores')
);
$getdata = $this->get($tablename, $arr);

$i = 1;
foreach ($getdata as $getdatum) {

    $scheme[] = $getdatum['id'].'_'.$i.':decimal:3,2';
    $i++;
}

$scheme[] = 'activo:int';

$this->createtable($tablename, $scheme);
```

**Comment by gobseck0** [comment]
> > Hi! I have an issue with the createtable(); function, I cannot make it work if you create the array ($scheme) from a fetch loop:
> > Do you know how can I build the $scheme array by a loop?
> > Thanks in advance.
> 
> Hi, if I understand correctly, you want to do something like this?
> 
> ```
> 
> $tablename = '2_1_5C';
> 
> $scheme = array();
> $scheme[] = 'idc:int'; //idc:increments ?
> 
> $arr = array(
>     'column'=>array('id', 'scores')
> );
> $getdata = $this->get($tablename, $arr);
> 
> $i = 1;
> foreach ($getdata as $getdatum) {
> 
>     if($getdatum['scores']>=$i){
>         $scheme[] = $getdatum['id'].'_'.$i.':decimal:3,2';
>         $i++;
>     }
> }
> 
> $scheme[] = 'activo:int';
> 
> $this->createtable($tablename, $scheme);
> ```

Thanks a lot, it was something like that what I need, I didn't know I can construct the array with the brackets, that help me a lot, thats why I was using "array_push", now it's working. As you probably know already, I'm newby in this, so I really appreciate your help.

**Comment by aliyilmaz** [comment]
You're welcome. In fact, I think you don't need to re-create an existing table, you can use `$this-> createcolumn` instead of `$this-createtable`.

#### Example

```
$tablename = '2_1_5C';

$scheme[] = 'idc:int'; //idc:increments ?

$arr = array(
    'column'=>array('id', 'scores')
);
$getdata = $this->get($tablename, $arr);

$i = 1;
foreach ($getdata as $getdatum) {

    if($getdatum['scores']>=$i){
        $scheme[] = $getdatum['id'].'_'.$i.':decimal:3,2';
        $i++;
    }
}

$scheme[] = 'activo:int';

$this->createcolumn($tablename, $scheme);
```

**Comment by gobseck0** [comment]
> > > Hi! I have an issue with the createtable(); function, I cannot make it work if you create the array ($scheme) from a fetch loop:
> > > Do you know how can I build the $scheme array by a loop?
> > > Thanks in advance.
> > 
> > 
> > Hi, if I understand correctly, you want to do something like this?
> > ```
> > 
> > $tablename = '2_1_5C';
> > 
> > $scheme = array();
> > $scheme[] = 'idc:int'; //idc:increments ?
> > 
> > $arr = array(
> >     'column'=>array('id', 'scores')
> > );
> > $getdata = $this->get($tablename, $arr);
> > 
> > $i = 1;
> > foreach ($getdata as $getdatum) {
> > 
> >     if($getdatum['scores']>=$i){
> >         $scheme[] = $getdatum['id'].'_'.$i.':decimal:3,2';
> >         $i++;
> >     }
> > }
> > 
> > $scheme[] = 'activo:int';
> > 
> > $this->createtable($tablename, $scheme);
> > ```
> 
> Thanks a lot, it was something like that what I need, I didn't know I can construct the array with the brackets, that help me a lot, thats why I was using "array_push", now it's working. As you probably know already, I'm newby in this, so I really appreciate your help.

Hi again, I have a new issue, I tried to replicate this idea to create an array to use with $this->insert($tablename,$scheme); but looks like doesn't work, I only get an "false" response with this.
Can you replicate this example with the insert function?

**Comment by aliyilmaz** [comment]
Hi, it would be nice to add and update multiple records, thanks. I added it to to-do list.
