### ISSUE TITLE
how to seach in multiple tables?

### ISSUE THREAD

**Issue by gobseck0** [aliyilmaz/Mind#7]
Hi, I just download the last version of Mind, and well, look very good, but I'm trying to find the way to do an inner join but I can't find how? I need to do the following in sql, but I want to know if there's a function inside Mind to do the same:

$sql = "SELECT * FROM table1 INNER JOIN table2 ON table1.id_s=table2.id_s WHERE table1.id_a =1 order by table2.id_s2";

The main idea it's to do a INNER JOIN or Left Join or something that can show the result of a seach in 2 or more tables.

I hope you can help me with that.

Carlos.

**Comment by aliyilmaz** [comment]
Hello carlos, good to see you again. Multi-table support is currently not available. I will make it in the new version. Thank you for your suggestion.

**Comment by gobseck0** [comment]
Hi, thanks for your answer. I have another question, or maybe suggestion, is there a way to use Mind with classic mysql queries? something like:

$myownquery = "SELECT * FROM table1 INNER JOIN table2 ON table1.id_s=table2.id_s WHERE table1.id_a =1 order by table2.id_s2";
this->print_pre($this->myownquery());

I know this is not the purpose of Mind, but I think will be usefull for some people like me.

Best regards.

**Comment by aliyilmaz** [comment]
You're right, this idea will give the developer more opportunity to act in a more practical way.

**Comment by aliyilmaz** [comment]
> Hi, thanks for your answer. I have another question, or maybe suggestion, is there a way to use Mind with classic mysql queries? something like:
> 
> $myownquery = "SELECT * FROM table1 INNER JOIN table2 ON table1.id_s=table2.id_s WHERE table1.id_a =1 order by table2.id_s2";
> this->print_pre($this->myownquery());
> 
> I know this is not the purpose of Mind, but I think will be usefull for some people like me.
> 
> Best regards.

Hi Carlos,

With getData, data can now be obtained from many tables. You can use the query method for your other suggestion. 

So:
$data = $this->query('SELECT * FROM table1 INNER JOIN table2 ON table1.id_s=table2.id_s WHERE table1.id_a =1 order by table2.id_s2');
$this->print_pre($data->fetchALL(PDO::FETCH_ASSOC));

**Comment by aliyilmaz** [comment]
https://github.com/aliyilmaz/Mind/releases/tag/4.4.1

**Comment by gobseck0** [comment]
Hi again, thanks for the update, but I have a question, what happens if I need the result of 

$this->print_pre($data->fetchALL (PDO :: FETCH_ASSOC));   

to be an array that can I use in a "foreach" setence, I want to create a html table with the result of the query, so the "print_pre" function is not exactly what I need.

**Comment by aliyilmaz** [comment]
Hi Carlos,

I wanted to use the print_pre method so that you could see the output on the screen.

You can use such as the following.

$rows = $data->fetchALL(PDO :: FETCH_ASSOC));
foreach($rows as $column => $row){
// $row['title'] or...
}

// total
$total = count($rows);
echo $total;
