### ISSUE TITLE
Update or insert notifications by email

### ISSUE THREAD

**Issue by gobseck0** [aliyilmaz/Mind#9]
Hi!

I write you because I've been trying to make another library works without success (phpmailer) I think my hosting services do not provide support for that library (specially the smtp output), anyway, I have a new suggestion for you, maybe you find it interesting, the idea is to send an email to someone when a table is updated or have an insert query, just like some notification or reminder.

This could be a new function related to insert or update, when you get a "success" response from the mysql query, something like: "sendNotification" or something like that.

I hope you find this idea useful.

Regards.

Carlos.

**Comment by aliyilmaz** [comment]
Hello, Carlos, Yes, I agree with you. It would be nice. He still couldn't develop a more stable method of sending php mail. It condemns developers to package addictions. For this reason, I think periodically about the idea of creating a brilliantly prepared method of sending mail without packet dependence.

Regards.
